name: Terraform CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  # ==========================================================
  # JOB 1: Terraform Plan
  # ==========================================================

  terraform-plan:

    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/dev

    steps:

      # 1. Checkout main branch
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Authentication
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Generate Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 7. Show Terraform Plan
      - name: Show Terraform Plan
        run: terraform show tfplan

      # 8. Upload plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-cd
          path: environment/dev/tfplan


  # ==========================================================
  # JOB 2: Terraform Apply
  # ==========================================================

  terraform-apply:

    name: Terraform Apply

    # Apply job starts only after Plan succeeds
    needs:
      - terraform-plan

    runs-on: ubuntu-latest

    # IMPORTANT:
    # This environment will provide the approval gate
    environment:
      name: production

    defaults:
      run:
        working-directory: environment/dev

    steps:

      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Authentication
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Download the exact plan generated by Plan job
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-cd
          path: environment/dev

      # 6. Apply the approved Terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan